"""added work hours in the attendance model.

Revision ID: 19dd6239abdc
Revises: af28fab3f639
Create Date: 2026-01-27 20:45:47.588540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd6239abdc'
down_revision = 'af28fab3f639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worked_hours', sa.Float(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('Present', 'Absent', 'Late', name='attendance_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Present', 'Absent', 'Late', name='attendance_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('worked_hours')

    # ### end Alembic commands ###
