"""added is active column in both service and category

Revision ID: 2627832d35c9
Revises: 1651c1acc7cc
Create Date: 2025-12-15 14:10:41.106402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2627832d35c9'
down_revision = '1651c1acc7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
