"""Initial migration.

Revision ID: 53835d03bbc5
Revises: 2627832d35c9
Create Date: 2025-12-15 20:50:01.088482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53835d03bbc5'
down_revision = '2627832d35c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
