"""fix employee active index

Revision ID: 62355773933a
Revises: f07f9b722421
Create Date: 2025-12-21 14:45:35.637950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62355773933a'
down_revision = 'f07f9b722421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('idx_employee_date_status', ['employee_id', 'booking_date', 'status'], unique=False)
        batch_op.create_index('idx_user_bookings', ['user_id', 'booking_date', 'status'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employee_active', ['is_active', 'override_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_active')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('idx_user_bookings')
        batch_op.drop_index('idx_employee_date_status')

    # ### end Alembic commands ###
